src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Areas/Ebook/Pages/Home/Index.cshtml.cs
using AlFikr.FrontendUI.Entities;
using AlFikr.FrontendUI.Entities.Exceptions;
using AlFikr.FrontendUI.Web.HttpClients;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace AlFikr.FrontendUI.Web.Areas.Ebook.Pages.Home;

public class IndexModel : PageModelBase
{
	private readonly IEbookServiceApiClient ebookServiceApiClient;
	public List<ThemeEntity> Themes { get; set; }
	public List<EbookEntity> RecentEbooks { get; set; }

	public IndexModel(IEbookServiceApiClient ebookServiceApiClient)
	{
		this.ebookServiceApiClient = ebookServiceApiClient;
	}

	public void OnGet()
	{
		//Themes = ebookServiceApiClient.GetThemesAsync().Result;
		//RecentEbooks = ebookServiceApiClient.GetRecentEbooksAsync().Result;
	}

	public IActionResult OnPostCultureManagement(string culture, string returnUrl)
	{
		try
		{
			Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
			   new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });
		}
		catch (ApiException ex)
		{
			return HandleError(ex, nameof(culture));
		}
		catch (Exception ex)
		{
			return HandleError(ex.Message);
		}

		return LocalRedirect(returnUrl);
	}

	public IActionResult OnPostAdvancedSearch(AdvancedSearchEntity advancedSearchEntity)
	{
		try
		{

		}
		catch (ApiException ex)
		{
			return HandleError(ex, nameof(advancedSearchEntity));
		}
		catch (Exception ex)
		{
			return HandleError(ex.Message);
		}

		return Page();
	}
}

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/Modals/ModalImportDocuments.cshtml
@using AlFikr.FrontendUI.Entities;

<div class="modal fade" id="modalImportDocuments" aria-labelledby="formModal" aria-hidden="true" style="padding-top:4%">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom pb-3">
                <h5 class="modal-title">@localizer["Importer des œuvres suivant nos modèles"]</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="FileContentForm">
                    <fieldset class="scheduler-border">
                        <div class="border mb-3" style="padding: 6px !important;">
                            <div>
                                <i class="fa fa-check info pr-2"></i>
                                <span style="font-size:15px;">
                                    @localizer["Les données à importer doivent être stockées dans un fichier Excel ayant la structure comme mentionner dans ces templates :"]
                                    <a href="/Document/DataValidationExcelFile" class="alert-link">Documents.xlsm</a>
                                    @localizer["ou bien"]
                                    <a href="/Document/DataValidationCSVFile" class="alert-link"> Document.csv </a>
                                    @localizer["pour les fichiers"] <b style="color:#ecb43a">xlsx</b> et <b style="color:#ecb43a">csv</b> @localizer["ou en format"] <b style="color:#ecb43a">.mrc</b> et <b style="color:#ecb43a">.xml</b> @localizer["pour les fichiers"] <b style="color:#ecb43a">Marc21</b>.
                                </span>
                            </div>
                            <div>
                                <i class="fa fa-check info pr-2"></i>
                                <span style="font-size:15px;">
                                    @localizer["Prière de respecter le nom et l’ordre des colonnes ainsi que la nature de l’information que doit stocker chaque champ."]
                                </span>
                            </div>
                        </div>
                        <span class="tooltip-info pull-right border p-2" data-toggle="tooltip" data-placement="bottom" title="Choisissez le fichier">
                            <input name="FileContent" id="FileContent" accept=".mrc,.xml, .csv,.xlsm" type="file" />
                            <a class="btn btn-primary" href="#" onclick="ImportData()">@localizer["Importer"]</a>
                        </span>
                    </fieldset>
                </form>
            </div>
            <div class="modal-footer">
                <a href="javascript:void(0)" data-dismiss="modal" class="btn btn-secondary" style="margin-right: 0%;">@localizer["Annuler"]</a>
            </div>
        </div>
    </div>
</div>

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/Modals/_AdvancedSearchModalPartial.cshtml
@using AlFikr.FrontendUI.Entities
@model AdvancedSearchEntity;

<div class="modal fade" id="advancedSearchModal" tabindex="-1" aria-labelledby="formModal" aria-hidden="true" style="padding-top:10%">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row col-md-12">
                    <div class="col-md-12 text-center">
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h3 class="modal-title"><b>@localizer["Recherche Avancée"]</b></h3>
                    </div>
                </div>
                <hr />
                <form id="advancedSearchForm" method="post" asp-page-handler="AdvancedSearch" asp-area="Ebook" asp-page="/Home/Index">
                    <div id="advancedSearchRows">
                        <div class="row col-md-12 mb-2" id="advancedsearch">
                            <div class="col-md-1" style="padding-top:1%;text-align:right;font-weight:bold">
                                <label>@localizer["Dans"]</label>
                            </div>
                            <div class="col-md-3 text-left">
                                <select class="form-control" asp-for="AdvancedSearchEntities[0].Field">
                                    <option value="FullText" selected>@localizer["FullText"]</option>
                                    <option value="ISBN">@localizer["ISBN"]</option>
                                    <option value="DOI">@localizer["DOI"]</option>
                                    <option value="Abstract">@localizer["Abstract"]</option>
                                    <option value="Title">@localizer["Title"]</option>
                                    <option value="Author">@localizer["Author"]</option>
                                    <option value="Preface">@localizer["Preface"]</option>
                                    <option value="Theme">@localizer["Theme"]</option>
                                </select>
                            </div>
                            <div class="col-md-5" id="text">
                                <input asp-for="AdvancedSearchEntities[0].Expression" class="form-control" placeholder="@localizer["Expression"]" />
                            </div>
                            <div class="col-md-2">
                                <select class="form-control" asp-for="AdvancedSearchEntities[0].Operator">
                                    <option value="AND" selected>@localizer["Et"]</option>
                                    <option value="OR">@localizer["Ou"]</option>
                                    <option value="NEAR">@localizer["Près de"]</option>
                                    <option value="BUT">@localizer["Sauf"]</option>
                                </select>
                            </div>
                            <div class="col-md-1 text-right actions" style="margin: auto;">
                                <i class="fa fa-plus-circle" onclick="ManageRow(this)" style="cursor:pointer;font-size:30px;"></i>
                            </div>
                        </div>
                    </div>
                    <div class="row col-md-12 justify-content-end" style="padding-top:2%">
                        <button type="button" onclick="DeleteAllRows()" style="color: #fff;" class="btn btn-default m-1">@localizer["Effacer"]</button>
                        <button type="submit" style="color: #fff;" class="btn btnAdvancedSearch m-1">@localizer["Chercher"]</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/Modals/_AuthorInfoPartial.cshtml
@using AlFikr.FrontendUI.Entities

<!-- Modal -->
<div class="modal fade" id="authorsInfo" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="AuthorTitle" style="font-weight:bold">@localizer["Auteur"]</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row" id="infoAuthorbody">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color:#ecb43a;color:#ffffff">Close</button>
            </div>
        </div>
    </div>
</div>