src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Areas/Ebook/Pages/Home/Index.cshtml.cs
using AlFikr.FrontendUI.Entities;
using AlFikr.FrontendUI.Entities.Exceptions;
using AlFikr.FrontendUI.Web.HttpClients;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace AlFikr.FrontendUI.Web.Areas.Ebook.Pages.Home;

public class IndexModel : PageModelBase
{
	private readonly IEbookServiceApiClient ebookServiceApiClient;
	public List<ThemeEntity> Themes { get; set; }
	public List<EbookEntity> RecentEbooks { get; set; }

	public IndexModel(IEbookServiceApiClient ebookServiceApiClient)
	{
		this.ebookServiceApiClient = ebookServiceApiClient;
	}

	public void OnGet()
	{
		//Themes = ebookServiceApiClient.GetThemesAsync().Result;
		//RecentEbooks = ebookServiceApiClient.GetRecentEbooksAsync().Result;
	}

	public IActionResult OnPostCultureManagement(string culture, string returnUrl)
	{
		try
		{
			Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
			   new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });
		}
		catch (ApiException ex)
		{
			return HandleError(ex, nameof(culture));
		}
		catch (Exception ex)
		{
			return HandleError(ex.Message);
		}

		return LocalRedirect(returnUrl);
	}

	public IActionResult OnPostAdvancedSearch(AdvancedSearchEntity advancedSearchEntity)
	{
		try
		{

		}
		catch (ApiException ex)
		{
			return HandleError(ex, nameof(advancedSearchEntity));
		}
		catch (Exception ex)
		{
			return HandleError(ex.Message);
		}

		return Page();
	}
}

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/ErrorMessageAlert.cshtml
@model string
@if(!string.IsNullOrEmpty(Model)){
    <div class="alert alert-danger" role="alert">
        @Model
    </div>
}

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/_Culture.cshtml
@{
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var culturelist = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<!-- Language -->
<div>
    <div class="language">
        <form id="cultureform" asp-area="Ebook" asp-page="/Home/Index" asp-page-handler="CultureManagement" asp-route-returnUrl="@returnUrl" method="post">
            <a class="nav-link dropdown-toggle" style="font-size:14px;" href="#" data-bs-toggle="dropdown"> <img id="current-culture" src="~/images/flag-@(culture.RequestCulture.UICulture.Name).png" alt="@culture.RequestCulture.UICulture.Name" />&nbsp; @culturelist.Find(x => x.Value == culture.RequestCulture.UICulture.Name).Text</a>
            <div class="dropdown-menu">
                <input id="culture" type="hidden" name="culture" value="" />
                @foreach (var item in culturelist)
                {
                    if (item.Value != @culture.RequestCulture.UICulture.Name)
                    {
                        <a class="dropdown-item selectedarea" style="font-size:14px;" onclick="setLang('@item.Value')"><img src="~/images/flag-@(item.Value).png" alt="@item.Value" />&nbsp; @item.Text</a>
                    }
                }
            </div>
        </form>
    </div>
</div>

<!-- End Language -->
<script>
    function setLang(x) {
        $('.se-pre-con').show();
        $('#culture').val(x);
        $('#cultureform').submit();
    }
</script>

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/_Layout.cshtml
@using AlFikr.FrontendUI.Entities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlFikr.FrontendUI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/keyboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlFikr.FrontendUI.Web.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/images/logo.png" />
    <link rel='shortcut icon' type='image/x-icon' href='~/images/favicon.ico' />
    <link href="~/css/keyboard.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css">
    <link rel="stylesheet" href="~/lib/izitoast/css/iziToast.min.css">
</head>
<body>
    <div class="se-pre-con"></div>
    <div class="loading" id="loading" hidden="hidden"></div>
    <div id="top-content">
        <div class="header-container">
            <header class="top-header">
                <div class="top-menu">
                    <div class="container">
                        <div class="row justify-content-between has-border">
                            <div class="col-2 col-md-2">
                                <partial name="_Culture" />
                            </div>
                            <div class="col-2 col-md-2">
                            </div>
                            <div class="col-4 col-md-4">
                                <div class="compte text-center">
                                    <label style="cursor: pointer;font-size:13px" onclick="">@localizer["Vous accédez à al-fikr via"]</label>
                                </div>
                            </div>
                            <div class="col-4 col-md-4">
                                <div class="compte text-right" id="login">
                                    <a onclick="Signup()" style=" cursor: pointer; font-size: 12px">@localizer["S’inscrire"]</a>
                                    <span id="signupbarre"> | </span>
                                    <label id="account"><a id="acc" onclick="Login()" style="cursor: pointer;font-size: 12px">@localizer["Se connecter"]</a></label>
                                    <span id="myCart" class="p1 fa-stack fa-2x has-badge visible-lg" style="font-size:large;cursor:pointer" data-count="0">
                                        <i class="fa fa-shopping-cart fa-stack-1x xfa-inverse visible-lg"></i>
                                    </span>
                                </div>
                                <script>
                                    /*
                                    function login() {
                                        var url = window.location.href;
                                        window.location.href = "/account/login?returnUrl=" + url;
                                    }*/
                                    function Signup() {
                                        var url = window.location.href;
                                        window.location.href = `https://localhost:7262/Account/signup`;
                                    }


                                    function Login() {
                                                const clientId = '@Environment.GetEnvironmentVariable("ClientId")';
                                                const redirectUri ='@Environment.GetEnvironmentVariable("CallbackPath")'
                                                const authorizationEndpoint = '@Environment.GetEnvironmentVariable("AuthorizationEndpoint")';
                                                const responseType = 'code';

                                                const url = `${authorizationEndpoint}?response_type=${responseType}&client_id=${clientId}&redirect_uri=${redirectUri}`;

                                        /*
                                        const scope = 'openid profile email'; // Adjust scopes as needed
                                        const state = 'your_unique_state_value'; // Optional: A value to maintain state between the request and callback*/

                                        window.location.href = url;
                                    }
                                </script>
                            </div>
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="main-menu">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 col-md-3">
                                <div class="logo">
                                    <a href="/"><img onclick="$('.se-pre-con').show();" src="~/images/logo.png" alt="al-fikr" /></a>
                                </div>
                            </div>
                            <div class="col-12 col-md-9">
                                <div class="search-bloc clearfix">
                                    <form id="simplesearchForm" method="get" asp-page="/Home/Search" asp-area="Ebook" asp-route-searchTerm="">
                                        <div class="row text-center">
                                            <div class="col-md-8">
                                                <div class="input-search">
                                                    <input type="text" name="search" id="search" class="keyboardInput" />
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="input-submit">
                                                    <button type="button" onclick="simplesearch()" class="send-form">@localizer["Recherche Rapide"]</button>
                                                    <a asp-page="/AdvancedSearch" asp-route-query="example" class="search-filter selectedarea btn btn-primary">
                                                        @localizer["Recherche Avancée"]
                                                    </a>

                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>
    </div>
    <div>
        @RenderBody()
        <partial name="_CookieConsentPartial" />
    </div>
    <!-- Button trigger modal -->

    <partial name="~/Pages/Shared/Modals/_AdvancedSearchModalPartial.cshtml" model="new AdvancedSearchEntity()" />
    <partial name="~/Pages/Shared/Modals/_AuthorInfoPartial.cshtml" />
    <footer id="footer" class="text-center text-lg-start text-white"
            style="background-color: #424c50 ;font-family:Alegreya Sans SC">
        <section class="d-flex justify-content-between p-4"
                 style="background-color: #ecb43a;">
            <div class="mr-5">
                <span>@localizer["Get connected with us on social networks:"]</span>
            </div>
            <div>
                <a href="https://www.facebook.com/Justech.tn" target="_blank" class="text-white mr-4">
                    <i class="fa fa-facebook-f"></i>
                </a>
                <a href="https://www.youtube.com/channel/UC1tUKpSctGe6edvVo4Y5GRw" target="_blank" class="text-white mr-4">
                    <i class="fa fa-youtube"></i>
                </a>
                <a href="https://www.linkedin.com/company/justech-tn/mycompany/" target="_blank" class="text-white mr-4">
                    <i class="fa fa-linkedin"></i>
                </a>
            </div>
        </section>
        <section>
            <div class="container-fluid text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-1 col-xl-1 col-sm-0 ">
                    </div>
                    <div class="col-md-2 col-sm-4 col-lg-2 col-xl-2 mx-auto mb-4">
                        <img src="~/images/logo-justpublish.png" style=" height:50px;width:250px">
                        <div>
                            <span class="row" style="flex-wrap:nowrap;">
                                <p class="col-7 my-auto mx-0 p-0">@localizer["Avec le soutien de"]</p>
                                <a class="col" href="http://www.cpu.rnu.tn/" target="_blank"><img src="/images/cpu_logo.png" style="width:90px;/* height:50px; */" alt=""></a>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2 col-lg-2 col-sm-4 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold text-left" style="border-bottom: solid 2px #ecb43a;">@localizer["Our Content"] </h6>
                        <div class="text-left">
                            <p class="m-0">
                                <a asp-action="OurProduct" asp-controller="Home" class="text-white" data-toggle="tooltip" data-placement="left" title="Tooltip on left"> @localizer["Al-fikr"]  </a>
                            </p>
                            <p class="m-0">
                                <a asp-action="OurProduct" asp-controller="Home" class="text-white"> @localizer["Al-fikrPublish"]  </a>
                            </p>
                            <p class="m-0">
                                <a asp-action="OurProduct" asp-controller="Home" class="text-white"> @localizer["Al-fikrSoft"] </a>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-2 col-lg-2 col-sm-4 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold text-left" style="border-bottom: solid 2px #ecb43a;">@localizer["HELP & CONTACTS"]</h6>
                        <div class="text-left">
                            <p class="m-0">
                                <a asp-action="conditions" asp-controller="Home" class="text-white">@localizer["Terms of Services"]</a>
                            </p>
                            <p class="m-0">
                                <a asp-action="PrivacyTerms" asp-controller="Home" class="text-white">@localizer["Privacy statement"]</a>
                            </p>
                            <p class="m-0">
                                <a asp-action="Contact" asp-controller="Home" class="text-white">@localizer["Contact us"]</a>
                            </p>
                            <p class="m-0">
                                <a href="#!" class="text-white">@localizer["Help"]</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-2 col-sm-4 col-xl-2 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold text-left" style="border-bottom: solid 2px #ecb43a;">@localizer["CONTACT"]</h6>
                        <div class="text-left">
                            <p class="m-0"><i class="fa fa-home mr-3" style="color:#ecb43a"></i> @localizer["Avenue Ali Bourguiba, résidence l'excellence, 5000 Monastir"]  </p>
                            <p class="m-0"><i class="fa fa-envelope mr-3" style="color:#ecb43a"></i> info@al-fikr.com</p>
                            <p class="m-0"><i class="fa fa-phone mr-3" style="color:#ecb43a"></i> +216 52 528 300</p>
                        </div>
                    </div>
                    <div class="col-md-2 col-xl-2 col-sm-4 ">
                        <div class="text-center mx-auto my-auto">
                            <img src="~/images/logo-startup-act.png" style="width:80px">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="text-center p-3 text-right"
             style="background-color: #3c3d3d;color:#ecb43a">
            © @DateTime.Now.Year @localizer["copyright"]
            <a style="color:#ecb43a" href="https://justech.tn/">Justech.tn</a>
        </div>
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/keyboard.js"></script>
    <script src="~/js/_AdvancedSearchModalPartial.js" asp-append-version="true"></script>
    <script src="~/js/isotope.min.js"></script>
    <script src="~/lib/izitoast/js/iziToast.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/al-fikr-frontend-ui/AlFikr.FrontendUI.Web/Pages/Shared/_Layout_Profile.cshtml
@using AlFikr.FrontendUI.Entities
<!DOCTYPE html>
<html lang="en">

<!-- blank.html  21 Nov 2019 03:54:41 GMT -->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Al-Fikr</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/app.min.css">
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel='shortcut icon' type='image/x-icon' href='~/images/favicon.ico' />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <link rel="stylesheet" type="text/css" href="~/css/select2.min.css">
    <link rel="stylesheet" href="~/css/components.css">
</head>

<body class="sidebar">
    <div class="loader"></div>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <nav class="navbar navbar-expand-lg main-navbar sticky">
                <div class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li>
                            <a href="#" data-toggle="sidebar" class="nav-link nav-link-lg
							collapse-btn"> <i data-feather="align-justify"></i></a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown"
                           class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="~/images/avatar.png"
                                 class="user-img-radious-style"> <span class="d-sm-none d-lg-inline-block"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right pullDown">
                            <div class="dropdown-title">@localizer["Bienvenu"] @User.Identity.Name</div>
                            <a href="/account/profil" class="dropdown-item has-icon">
                                <i class="fas fa-user"></i>@localizer["Profil"]
                            </a>
                            <div class="dropdown-divider"></div>
                            <a asp-action="Logout" asp-controller="Account" class="dropdown-item has-icon text-danger">
                                <i class="fas fa-sign-out-alt"></i>
                                @localizer["Se déconnecter"]
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="main-sidebar sidebar-style-2 sticky">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a asp-page="/Home/Index" asp-area="Ebook">
                            <img alt="image" src="~/images/logo.png" class="header-logo" />
                        </a>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="menu-header">Main</li>
                        <li class="dropdown">
                            <a asp-page="/Document/Index" asp-area="Admin" class="nav-link toggled" data-toggle="tooltip" data-placement="right"><i class="fas fa-book"></i><span>@localizer["Publications"]</span></a>
                        </li>
                        <li class="dropdown">
                            <a asp-page="/Thesis/Index" asp-area="Admin" class="nav-link toggled" data-toggle="tooltip" data-placement="right"><i class="fas fa-book"></i><span>@localizer["Theses"]</span></a>
                        </li>
                        <li class="dropdown">
                            <a asp-page="/Author/Index" asp-area="Admin" class="nav-link toggled" data-toggle="tooltip" data-placement="right"><i class="fas fa-user-secret"></i><span>@localizer["Auteurs"]</span></a>
                        </li>
                        <li class="dropdown">
                            <a asp-page="/Theme/Index" asp-area="Admin" class="nav-link toggled" data-toggle="tooltip" data-placement="right"><i class="fas fa-th"></i><span>@localizer["Themes"]</span></a>
                        </li>
                        <li class="dropdown">
                            <a asp-page="/Collection/Index" asp-area="Admin" class="nav-link toggled" data-toggle="tooltip" data-placement="right"><i class="fas fa-boxes"></i><span>@localizer["Collections"]</span></a>
                        </li>
                        <li id="users" class="dropdown">
                            <a href="#" class="menu-toggle nav-link has-dropdown"><i class="fas fa-users"></i><span>@localizer["Users"]</span></a>
                            <ul class="dropdown-menu">
                                <li class=" "><a class="nav-link" asp-page="/Editor/Index" asp-area="Admin">@localizer["Editors"]</a></li>
                                <li class=" "><a class="nav-link" asp-page="/Individual/Index" asp-area="Admin">@localizer["Individuals"]</a></li>
                            </ul>
                        </li>
                        @*
        <li class="dropdown">
            <a href="" class="nav-link toggled" data-toggle="tooltip" data-original-title="Catalogues" data-placement="right"><i class="fas fa-object-group"></i><span>Catalogues</span></a>
        </li>
        <li onclick="$('.loader').show()" class="dropdown">
            <a href="" class="nav-link toggled"><i class="fa fa-users"></i><span>Utilisateurs associés</span></a>
        </li>
        <li class="dropdown">
            <a href="" class="nav-link toggled" data-toggle="tooltip" data-original-title="Catalogues" data-placement="right"><i class="fas fa-object-group"></i><span>Catalogues</span></a>
        </li>
        <li onclick="" class="dropdown">
            <a href="" class="nav-link toggled" data-toggle="tooltip" data-original-title="Messages" data-placement="right"><i class="fa fa-comments"></i><span>Messages (1)</span></a>
        </li>
        <li onclick="" class="dropdown">
            <a href="" class="nav-link toggled" data-toggle="tooltip" data-original-title="Statistiques" data-placement="right"><i class="fa fa-line-chart"></i><span>Statistiques</span></a>
        </li> *@
                    </ul>
                </aside>
            </div>
           
            <!-- ModalImports -->
            <div class="modal fade" id="ModalImports" style="padding-top:4%">
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content">
                        <div class="modal-header border-bottom pb-3">
                            <h5 class="modal-title">Contenu à Importer</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="table-responsive">
                                <h6 class="modal-title mb-4 mt-2" id="DocumentError">Liste des documents invalide dans le fichiers : </h6>
                                <table id="InvalideDocumentsDataTable" class="table table-striped table-bordered" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Original Title</th>
                                            <th>ISBN</th>
                                            <th>Collection</th>
                                            <th>Etat</th>
                                            <th>Auteur</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                            <div class="table-responsive mt-3">
                                <h6 class="modal-title mt-2 mb-4" id="DocumentSuccess">Liste des documents insérés avec succès</h6>
                                <table id="ValideDocumentsDataTable" class="table table-striped table-bordered " width="100%">
                                    <thead>
                                        <tr>
                                            <th>Original Title</th>
                                            <th>ISBN</th>
                                            <th>Collection</th>
                                            <th>Etat</th>
                                            <th>Auteur</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a href="javascript:void(0)" data-dismiss="modal" class="btn btn-secondary" style="margin-right: 0%;">Annuler</a>
                            <button type="button" class="btn btn-primary" id="buttonsaveChanges" onclick="SaveDataToDatabase()"><i class="fa fa-check"></i> Enregistrer </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Main Content -->
            <div class="main-content">
                <section class="section">
                    <div class="section-body">
                        @RenderBody()
                    </div>
                </section>
            </div>
            @*<partial name="~/Pages/Shared/Modals/ModalImportDocuments.cshtml" model="new ImportDocumnetEntity()" />*@
            <!-- Footer -->
            <footer class="main-footer position-static">
                <div class="row">
                    <div class="col-md-12">
                        &copy; @DateTime.Today.Year - AL-Fikr
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
   @*  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> *@
    <script src="~/js/app.min.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="~/js/select2.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>